services:
  - type: web
    name: electricity-consumption-billing
    env: java
    plan: free
    buildCommand: chmod +x mvnw && ./mvnw package
    startCommand: java -jar target/ecb-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://your-mysql-host:3306/ecb_db
      - key: SPRING_DATASOURCE_USERNAME
        value: your-mysql-username
      - key: SPRING_DATASOURCE_PASSWORD
        value: your-mysql-password
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
      - key: GOOGLE_REDIRECT_URI
        value: https://your-app-name.onrender.com/login/oauth2/code/google
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: true
